name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: npm ci
      - name: Generate Prisma Client
        env:
          DATABASE_URL: file:./dev.db
        run: npx prisma generate
      - name: Typecheck
        run: npm run typecheck
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Run Playwright tests
        env:
          DATABASE_URL: file:./dev.db
        run: npx playwright install --with-deps && npm test 